/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIERC721,
  IIERC721Interface,
} from "../../../contracts/SamplePrimarySaleERC721.sol/IIERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IIERC721__factory {
  static readonly abi = _abi;
  static createInterface(): IIERC721Interface {
    return new Interface(_abi) as IIERC721Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IIERC721 {
    return new Contract(address, _abi, runner) as unknown as IIERC721;
  }
}
