/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IImmutableERC20Errors,
  IImmutableERC20ErrorsInterface,
} from "../../../../../../../../@imtbl/contracts/contracts/token/erc20/preset/Errors.sol/IImmutableERC20Errors";

const _abi = [
  {
    inputs: [],
    name: "RenounceOwnershipNotAllowed",
    type: "error",
  },
] as const;

export class IImmutableERC20Errors__factory {
  static readonly abi = _abi;
  static createInterface(): IImmutableERC20ErrorsInterface {
    return new Interface(_abi) as IImmutableERC20ErrorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IImmutableERC20Errors {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IImmutableERC20Errors;
  }
}
