/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as errorsSol from "./Errors.sol";
export { ImmutableERC20FixedSupplyNoBurn__factory } from "./ImmutableERC20FixedSupplyNoBurn__factory";
