/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errorsSol from "./Errors.sol";
export type { errorsSol };
export type { ImmutableERC20FixedSupplyNoBurn } from "./ImmutableERC20FixedSupplyNoBurn";
